export const failing = () => {
  throw new Error("This is a failing test");
};
